name: tests

on: [push]

jobs:
  check-installation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kicad-version: ['7.0']
    steps:
      - uses: actions/checkout@v3
      - name: Setup KiCad
        uses: ./
        with:
          node-version: ${{ matrix.kicad-version }}
      - name: Verify node and npm
        run: tests/verify-kicad.sh "${{ matrix.node-version }}"
        shell: bash